version: "3.0"
services:
  hostapd:
    image: debian
    build: './hostapd'
    privileged: true
    network_mode: "host"
  dnsmasq:
    image: debian
    build: './dns'
    privileged: true
    network_mode: "host"

